'use strict';
const $ = id => document.getElementById(id);
const fmt = (n, digits = 0) => Number(n || 0).toLocaleString(undefined, { maximumFractionDigits: digits });
const compact = n => Math.abs(n) >= 1e6 ? `${+(n / 1e6).toFixed(1)}m` : Math.abs(n) >= 1000 ? `${+(n / 1000).toFixed(1)}k` : `${+n.toFixed(1)}`;
const esc = x => String(x ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const sum = (rows, fn = r => Math.abs(r.tokens)) => rows.reduce((a, r) => a + fn(r), 0);
const colors = ['var(--mint)', 'var(--violet)', '#d5a777', '#8baec7', '#cd91ab', '#a4b77b', '#c5bca3'];
const weekdays = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
const day = r => r.date.slice(0, 10), month = r => r.date.slice(0, 7);
const dateLabel = d => new Date(d).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric', timeZone: 'UTC' });
const friendly = s => String(s).replace(/([a-z])([A-Z])/g, '$1 $2').replace(/^./, c => c.toUpperCase());
let data = { transactions: [] }, reference = {}, filtered = [], spending = [], purchases = [], tableRows = [], page = 0, hiddenNames = false, aliases = new Map(), refreshToken = '', polling = false;
let theme = 'dark'; try { theme = localStorage.getItem('ledger-theme') || (matchMedia('(prefers-color-scheme: light)').matches ? 'light' : 'dark'); } catch { }
function setTheme(value) { theme = value === 'light' ? 'light' : 'dark'; document.documentElement.dataset.theme = theme; $('theme').innerHTML = theme === 'dark' ? '☼ <span>Light theme</span>' : '☾ <span>Dark theme</span>'; $('theme').setAttribute('aria-label', `Switch to ${theme === 'dark' ? 'light' : 'dark'} theme`); try { localStorage.setItem('ledger-theme', theme); } catch { } }
setTheme(theme);
const name = s => hiddenNames ? aliases.get(s) || 'Recipient' : s;
function grouped(rows, key, val = r => Math.abs(r.tokens)) { const map = new Map(); for (const r of rows) { const k = key(r); map.set(k, (map.get(k) || 0) + val(r)); } return [...map].sort((a, b) => b[1] - a[1]); }
function empty(id, text = 'No matching activity in this period.') { $(id).innerHTML = `<div class="empty">${esc(text)}</div>`; }
function table(id, headers, rows) { $(id).innerHTML = `<table><thead><tr>${headers.map(h => `<th scope="col">${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.length ? rows.map(r => `<tr>${r.map(c => `<td>${c}</td>`).join('')}</tr>`).join('') : `<tr><td colspan="${headers.length}">No matching records.</td></tr>`}</tbody></table>`; }
function stat(label, value, note, symbol) { return `<div class="stat"><div class="stat-label">${esc(label)}<span class="stat-symbol">${symbol}</span></div><div class="stat-number">${fmt(value, label === 'Average transaction' ? 1 : 0)}</div><div class="stat-note">${esc(note)}</div></div>`; }
function mini(label, value) { return `<div class="mini"><small>${esc(label)}</small><strong>${esc(value)}</strong></div>`; }
function bars(id, rows, { unit = 'tokens', color = colors[0], limit = 10 } = {}) { rows = rows.slice(0, limit); if (!rows.length) return empty(id); const max = Math.max(...rows.map(r => Math.abs(r[1])), 1); $(id).innerHTML = `<div class="bars">${rows.map(([label, value], i) => `<div data-tip="${esc(label)}: ${fmt(value, 2)} ${unit}"><div class="bar-label"><span>${esc(label)}</span><span>${fmt(value, 2)} ${unit}</span></div><div class="track"><div class="bar-fill" style="width:${Math.abs(value) / max * 100}%;background:${Array.isArray(color) ? color[i % color.length] : color}"></div></div></div>`).join('')}</div>`; }
function chart(id, labels, series, { kind = 'line', unit = 'tokens', height = 245, showPoints = false } = {}) {
    if (!labels.length || !series.some(s => s.values.some(v => v !== null))) return empty(id);
    const w = Math.max(320, $(id).clientWidth || 760), h = height, left = 52, right = 15, top = 20, bottom = 40, pw = w - left - right, ph = h - top - bottom;
    const values = series.flatMap(s => s.values).filter(v => v !== null && Number.isFinite(v));
    const min = Math.min(0, ...values), max = Math.max(1, ...values), span = max - min;
    const y = v => top + ph - (v - min) / span * ph;
    const x = i => left + (kind === 'bar' ? (i + .5) / labels.length : labels.length === 1 ? .5 : i / (labels.length - 1)) * pw;
    let svg = `<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="${esc($(id).closest('article')?.querySelector('h3')?.textContent || id)}"><title>${esc(unit)} by ${esc(labels.length)} categories. Hover marks for exact values.</title>`;
    for (let i = 0; i <= 4; i++) { const v = min + span * i / 4; svg += `<line class="gridline" x1="${left}" y1="${y(v)}" x2="${w - right}" y2="${y(v)}"/><text x="${left - 9}" y="${y(v) + 3}" text-anchor="end">${compact(v)}</text>`; }
    const step = Math.max(1, Math.ceil(labels.length / Math.max(2, Math.floor(pw / 85))));
    labels.forEach((label, i) => { if (i % step === 0 || i === labels.length - 1 && labels.length > 1 && i % step > step / 2) svg += `<text x="${x(i)}" y="${h - 12}" text-anchor="middle">${esc(label)}</text>`; });
    series.forEach((s, si) => {
        const color = s.color || colors[si % colors.length];
        if (kind === 'bar') {
            const bw = Math.min(45, pw / labels.length * .7 / series.length);
            s.values.forEach((v, i) => { if (v === null) return; svg += `<rect x="${x(i) + (si - series.length / 2) * bw}" y="${Math.min(y(v), y(0))}" width="${Math.max(.4, bw - 2)}" height="${Math.max(1, Math.abs(y(v) - y(0)))}" rx="2" fill="${color}" data-tip="${esc(labels[i])} · ${esc(s.name)}: ${fmt(v, 2)} ${unit}"><title>${esc(labels[i])}: ${fmt(v, 2)} ${unit}</title></rect>`; });
        } else {
            let d = '', active = false; s.values.forEach((v, i) => { if (v === null) { active = false; return; } d += `${active ? 'L' : 'M'}${x(i)},${y(v)} `; active = true; });
            svg += `<path d="${d}" fill="none" stroke="${color}" stroke-width="2.4" stroke-linejoin="round" stroke-linecap="round"/>`;
            s.values.forEach((v, i) => { if (v === null) return; svg += `<circle cx="${x(i)}" cy="${y(v)}" r="${showPoints || labels.length < 16 ? 3 : 2}" fill="${color}" data-tip="${esc(labels[i])} · ${esc(s.name)}: ${fmt(v, 2)} ${unit}"><title>${esc(labels[i])}: ${fmt(v, 2)} ${unit}</title></circle>`; });
        }
    });
    svg += '</svg>'; $(id).innerHTML = svg;
}
function rangeDays(start, end) { const a = []; if (!start || !end) return a; let d = new Date(start + 'T00:00:00Z'); const last = new Date(end + 'T00:00:00Z'); for (let i = 0; d <= last && i < 40000; i++, d.setUTCDate(d.getUTCDate() + 1))a.push(d.toISOString().slice(0, 10)); return a; }
function monthRange(start, end) { const a = []; if (!start || !end) return a; let d = new Date(start.slice(0, 7) + '-01T00:00:00Z'), last = end.slice(0, 7); for (let i = 0; i < 1200 && d.toISOString().slice(0, 7) <= last; i++, d.setUTCMonth(d.getUTCMonth() + 1))a.push(d.toISOString().slice(0, 7)); return a; }
function shortMonth(s) { return new Date(s + '-01T00:00:00Z').toLocaleDateString('en', { month: 'short', year: '2-digit', timeZone: 'UTC' }); }
function selectedBounds() { return [$('from').value || (filtered[0]?.date.slice(0, 10)), $('to').value || filtered.at(-1)?.date.slice(0, 10)]; }
function render() {
    const from = $('from').value, to = $('to').value, mode = $('mode').value;
    if (from && to && from > to) { message('The start date must be on or before the end date.', true); return; }
    filtered = data.transactions.filter(r => (!from || day(r) >= from) && (!to || day(r) <= to) && (mode === 'all' || r.vr === (mode === 'vr')));
    spending = filtered.filter(r => r.spending); purchases = filtered.filter(r => r.purchase); page = 0;
    $('scope').textContent = `${fmt(filtered.length)} records`;
    const spent = sum(spending), bought = sum(purchases), active = new Set(spending.map(day)).size, users = new Set(spending.map(r => r.username)).size, vr = sum(spending.filter(r => r.vr));
    $('stats').innerHTML = stat('Tokens spent', spent, `${fmt(spending.length)} spending transactions`, '↗') + stat('Tokens purchased', bought, `${fmt(purchases.length)} top-ups in this period`, '↓') + stat('Recipients', users, `${fmt(active)} active spending days`, '♧') + stat('Average transaction', spending.length ? spent / spending.length : 0, `${fmt(active ? spent / active : 0, 1)} tokens per active day`, '⌁');
    const [start, end] = selectedBounds(), months = monthRange(start, end), days = rangeDays(start, end);
    const sp = new Map(grouped(spending, month)), pu = new Map(grouped(purchases, month)), daily = new Map(grouped(spending, day)), puday = new Map(grouped(purchases, day));
    chart('monthly-chart', months.map(shortMonth), [{ name: 'Purchased', values: months.map(m => pu.get(m) || 0) }, { name: 'Spent', values: months.map(m => sp.get(m) || 0) }], { kind: 'bar' });
    let cs = 0, cp = 0; chart('cumulative-chart', days, [{ name: 'Purchased', values: days.map(d => cp += puday.get(d) || 0) }, { name: 'Spent', values: days.map(d => cs += daily.get(d) || 0) }]);
    if (spent) { const pct = vr / spent * 100, circ = 2 * Math.PI * 70; $('vr-chart').innerHTML = `<div class="donut-wrap"><svg viewBox="0 0 200 200" role="img" aria-label="VR ${pct.toFixed(1)} percent of spending"><circle cx="100" cy="100" r="70" fill="none" stroke="var(--violet)" stroke-width="19"/><circle cx="100" cy="100" r="70" fill="none" stroke="var(--mint)" stroke-width="19" stroke-dasharray="${circ * pct / 100} ${circ}"/></svg><div class="donut-center">${fmt(pct, 1)}%<span>OF SPENDING IN VR</span></div></div><div class="donut-legend"><div><span class="local-dot"></span>VR<strong>${fmt(vr)} tokens</strong></div><div>◦ Non-VR<strong>${fmt(spent - vr)} tokens</strong></div></div>`; } else empty('vr-chart');
    table('vr-table', ['Mode', 'Tokens', 'Transactions', 'Share of spending', 'Average / transaction'], [true, false].map(mode => { const rows = spending.filter(r => r.vr === mode), total = sum(rows); return [mode ? 'VR' : 'Non-VR', fmt(total), fmt(rows.length), `${fmt(spent ? total / spent * 100 : 0, 1)}%`, fmt(rows.length ? total / rows.length : 0, 2)]; }));
    $('history-range').textContent = filtered.length ? `Selected history: ${filtered[0].date.replace('T', ' ').replace('Z', ' UTC')} to ${filtered.at(-1).date.replace('T', ' ').replace('Z', ' UTC')}.` : 'No transactions in the selected period.';
    const monthlyRows = months.map((m, i) => { const rows = spending.filter(r => month(r) === m), total = sum(rows), vr = sum(rows.filter(r => r.vr)), days = new Set(rows.map(day)).size, prev = sp.get(months[i - 1]) || 0; return [esc(m), fmt(pu.get(m)), fmt(total), fmt(vr), fmt(total - vr), fmt(rows.length), fmt(new Set(rows.map(r => r.username)).size), fmt(days), fmt(rows.length ? total / rows.length : 0, 1), fmt(days ? total / days : 0, 1), `${fmt(total ? vr / total * 100 : 0, 1)}%`, prev ? `${fmt((total - prev) / prev * 100, 1)}%` : '—']; });
    table('monthly-table', ['Month', 'Purchased', 'Spent', 'VR', 'Non-VR', 'Transactions', 'Recipients', 'Days', 'Avg / txn', 'Avg / day', 'VR share', 'MoM'], monthlyRows);
    $('purchase-stats').innerHTML = mini('Total purchased', `${fmt(bought)} tokens`) + mini('Average top-up', `${fmt(purchases.length ? bought / purchases.length : 0, 1)} tokens`) + mini('Largest top-up', `${fmt(Math.max(0, ...purchases.map(r => r.tokens)))} tokens`) + mini('Other net adjustments', `${fmt(sum(filtered.filter(r => !r.spending && !r.purchase), r => r.tokens))} tokens`);
    chart('purchase-chart', purchases.map(r => day(r)), [{ name: 'Purchase', values: purchases.map(r => r.tokens) }], { kind: 'bar' });
    bars('flow-chart', grouped(filtered, r => `${r.tokens >= 0 ? 'In' : 'Out'} · ${friendly(r.type)}`), { color: colors, limit: 30 });
    const net = new Map(grouped(filtered, day, r => r.tokens)); let balance = 0; chart('net-chart', days, [{ name: 'Net movement', values: days.map(d => balance += net.get(d) || 0) }]);
    bars('package-chart', grouped(purchases, r => `${fmt(r.tokens)} tokens`, () => 1), { unit: 'purchases' });
    const totals = data.api_totals || {}; $('api-totals').innerHTML = Object.keys(totals).length ? Object.entries(totals).map(([k, v]) => `<div>${esc(k)} <strong>${esc(typeof v === 'number' ? fmt(v, 2) : String(v))}</strong></div>`).join('') + '<p>API-reported values for the full fetched date range. USD fields are not verified billing amounts.</p>' : 'Not present in the existing export. The next successful pull will preserve these API fields.';
    bars('type-chart', grouped(spending, r => friendly(r.type)), { color: colors, limit: 30 });
    table('type-table', ['Type', 'Tokens', 'Transactions', 'VR', 'Non-VR'], grouped(spending, r => r.type).map(([type, total]) => { const rows = spending.filter(r => r.type === type), vr = sum(rows.filter(r => r.vr)); return [esc(friendly(type)), fmt(total), fmt(rows.length), fmt(vr), fmt(total - vr)]; }));
    const bins = [[1, 9], [10, 49], [50, 99], [100, 499], [500, 999], [1000, Infinity]];
    chart('distribution-chart', bins.map(([a, b]) => b === Infinity ? '1,000+' : `${a}–${b}`), [{ name: 'Transactions', values: bins.map(([a, b]) => spending.filter(r => Math.abs(r.tokens) >= a && Math.abs(r.tokens) <= b).length) }], { kind: 'bar', unit: 'transactions' });
    chart('daily-chart', days, [{ name: 'Spent', values: days.map(d => daily.get(d) || 0) }]);
    chart('change-chart', months.map(shortMonth), [{ name: 'Change', color: colors[1], values: months.map((m, i) => { const prev = sp.get(months[i - 1]); return prev ? ((sp.get(m) || 0) - prev) / prev * 100 : null; }) }], { kind: 'bar', unit: '%' });
    bars('source-chart', grouped(spending, r => r.source), { color: colors });
    bars('largest-chart', [...spending].sort((a, b) => Math.abs(b.tokens) - Math.abs(a.tokens)).slice(0, 10).map(r => [`${name(r.username)} · ${day(r)}`, Math.abs(r.tokens)]), { color: colors[1] });
    const weekday = new Array(7).fill(0), hour = new Array(24).fill(0), heat = Array.from({ length: 7 }, () => new Array(24).fill(0));
    spending.forEach(r => { const d = new Date(r.date), w = (d.getUTCDay() + 6) % 7, h = d.getUTCHours(); weekday[w] += Math.abs(r.tokens); hour[h] += Math.abs(r.tokens); heat[w][h] += Math.abs(r.tokens); });
    chart('weekday-chart', weekdays.map(s => s.slice(0, 3)), [{ name: 'Spent', values: weekday }], { kind: 'bar' });
    chart('hour-chart', hour.map((_, i) => `${String(i).padStart(2, '0')}:00`), [{ name: 'Spent', values: hour }], { kind: 'bar' });
    renderHeatmap(heat); renderCalendar(daily, days);
    const activityRows = (keys, fn) => keys.map((label, i) => { const rows = spending.filter(r => fn(r) === i), tokens = sum(rows); return [esc(label), fmt(tokens), fmt(rows.length), fmt(rows.length ? tokens / rows.length : 0, 1)]; });
    table('weekday-table', ['Weekday', 'Tokens', 'Transactions', 'Avg / txn'], activityRows(weekdays, r => (new Date(r.date).getUTCDay() + 6) % 7));
    table('hour-table', ['UTC hour', 'Tokens', 'Transactions', 'Avg / txn'], activityRows(hour.map((_, i) => `${String(i).padStart(2, '0')}:00`), r => new Date(r.date).getUTCHours()));
    const people = [...new Set(spending.map(r => r.username))].map(username => { const r = spending.filter(r => r.username === username), tokens = sum(r), vr = sum(r.filter(t => t.vr)); return { username, tokens, vr, count: r.length, days: new Set(r.map(day)).size }; }).sort((a, b) => b.tokens - a.tokens);
    bars('people-chart', people.map(p => [name(p.username), p.tokens])); bars('frequency-chart', [...people].sort((a, b) => b.count - a.count).map(p => [name(p.username), p.count]), { unit: 'transactions', color: colors[1] });
    table('people-table', ['Recipient', 'Tokens', 'Share', 'VR', 'Non-VR', 'Transactions', 'Active days', 'Avg / txn', 'VR share'], people.map(p => [esc(name(p.username)), fmt(p.tokens), `${fmt(spent ? p.tokens / spent * 100 : 0, 1)}%`, fmt(p.vr), fmt(p.tokens - p.vr), fmt(p.count), fmt(p.days), fmt(p.tokens / p.count, 1), `${fmt(p.vr / p.tokens * 100, 1)}%`]));
    renderTransactions();
}
function renderHeatmap(rows) { const max = Math.max(1, ...rows.flat()), cell = 27; let svg = '<svg viewBox="0 0 730 240" role="img" aria-label="Spending heatmap by weekday and UTC hour">'; for (let h = 0; h < 24; h += 2)svg += `<text x="${65 + h * cell}" y="14">${String(h).padStart(2, '0')}</text>`; rows.forEach((row, w) => { svg += `<text x="0" y="${43 + w * cell}">${weekdays[w].slice(0, 3)}</text>`; row.forEach((v, h) => { svg += `<rect x="${62 + h * cell}" y="${27 + w * cell}" width="22" height="22" rx="4" fill="var(--mint)" opacity="${v ? .22 + .78 * Math.sqrt(v / max) : .07}" data-tip="${weekdays[w]} ${String(h).padStart(2, '0')}:00 UTC: ${fmt(v)} tokens"><title>${fmt(v)} tokens</title></rect>`; }); }); svg += '</svg>'; $('heatmap-chart').innerHTML = svg; }
function renderCalendar(daily, allDays) { const days = allDays.slice(-365); if (!days.length) return empty('calendar-chart'); const offset = (new Date(days[0] + 'T00:00:00Z').getUTCDay() + 6) % 7, cols = Math.ceil((days.length + offset) / 7), max = Math.max(1, ...days.map(d => daily.get(d) || 0)); let svg = `<svg viewBox="0 0 ${cols * 15 + 45} 151" role="img" aria-label="Daily spending calendar">`;['Mon', 'Wed', 'Fri'].forEach((label, i) => svg += `<text x="0" y="${36 + i * 30}">${label}</text>`); days.forEach((d, i) => { const index = i + offset, x = 40 + Math.floor(index / 7) * 15, y = 25 + index % 7 * 15, v = daily.get(d) || 0; if (d.endsWith('-01') || i === 0) svg += `<text x="${x}" y="13">${new Date(d + 'T00:00:00Z').toLocaleDateString('en', { month: 'short', timeZone: 'UTC' })}</text>`; svg += `<rect x="${x}" y="${y}" width="11" height="11" rx="2" fill="var(--mint)" opacity="${v ? .23 + .77 * Math.sqrt(v / max) : .08}" data-tip="${d}: ${fmt(v)} tokens"><title>${d}: ${fmt(v)} tokens</title></rect>`; }); svg += `<text x="40" y="147">${days[0]} — ${days.at(-1)} · Hover a square to explore</text></svg>`; $('calendar-chart').innerHTML = svg; }
function renderTransactions() { const query = $('search').value.trim().toLowerCase(), category = $('category').value, sort = $('sort').value; tableRows = filtered.filter(r => (category === 'all' || category === 'purchase' && r.purchase || category === 'spending' && r.spending || category === 'adjustment' && !r.purchase && !r.spending) && `${name(r.username)} ${r.type} ${hiddenNames ? '' : r.id}`.toLowerCase().includes(query)); tableRows.sort((a, b) => sort === 'largest' ? Math.abs(b.tokens) - Math.abs(a.tokens) : sort === 'oldest' ? a.date.localeCompare(b.date) : b.date.localeCompare(a.date)); const pages = Math.max(1, Math.ceil(tableRows.length / 25)); page = Math.min(page, pages - 1); table('transaction-table', ['Date / UTC', 'Recipient', 'Type', 'Mode', 'Tokens', 'Category', 'Transaction ID'], tableRows.slice(page * 25, page * 25 + 25).map(r => [esc(r.date.replace('T', ' ').replace('Z', '')), esc(name(r.username)), esc(friendly(r.type)), `<span class="badge">${r.vr ? 'VR' : 'NON-VR'}</span>`, `<span class="${r.tokens >= 0 ? 'positive' : 'negative'}">${r.tokens > 0 ? '+' : ''}${fmt(r.tokens)}</span>`, r.purchase ? 'Purchase' : r.spending ? 'Spending' : 'Adjustment / other', hiddenNames ? 'Hidden' : esc(r.id)])); $('page-info').textContent = `${fmt(tableRows.length)} transactions · Page ${page + 1} of ${pages}`; $('prev').disabled = page === 0; $('next').disabled = page >= pages - 1; }
function renderReferences() {
    const methods = Object.keys(reference).filter(k => k.endsWith('_packages')), selected = $('payment-method').value, shown = selected === 'all' ? methods : methods.filter(m => m === selected);
    const prices = [...new Set(methods.flatMap(m => reference[m].map(p => p.price)))].sort((a, b) => a - b);
    chart('value-chart', prices.map(p => `€${fmt(p, 2)}`), shown.map(m => ({ name: friendly(m.replace('_packages', '')), color: colors[methods.indexOf(m)], values: prices.map(price => { const p = reference[m].find(p => p.price === price); return p ? p.tokens / p.price : null; }) })), { unit: 'tokens / €', height: 285, showPoints: true });
    $('value-legend').innerHTML = shown.map(m => `<span style="--c:${colors[methods.indexOf(m)]}">${esc(friendly(m.replace('_packages', '')))}</span>`).join('');
    table('value-table', ['Package price', ...shown.map(m => friendly(m.replace('_packages', '')))], prices.map(price => [`€${fmt(price, 2)}`, ...shown.map(m => { const p = reference[m].find(p => p.price === price); return p ? `${fmt(p.tokens)} tokens · ${fmt(p.tokens / price, 2)} / €` : '—'; })]));
    const xp = Object.entries(reference.xp_by_level || {}); chart('xp-chart', xp.map(([level]) => level), [{ name: 'Total XP', values: xp.map(([, v]) => v) }], { unit: 'XP' }); chart('xp-step-chart', xp.slice(1).map(([level]) => level), [{ name: 'Additional XP', color: colors[1], values: xp.slice(1).map(([, v], i) => v - xp[i][1]) }], { unit: 'XP' }); renderLevel();
}
function renderLevel() { const level = Number($('level').value), xp = reference.xp_by_level || {}; $('level-value').textContent = level; $('level-stats').innerHTML = `<strong>${fmt(xp[level])} XP</strong> to reach level ${level}<br>${level < 100 ? `<strong>${fmt(xp[level + 1] - xp[level])} XP</strong> to the next level` : 'Highest reference level'}`; }
function message(text, error = false) { $('status').textContent = text; $('status').classList.toggle('error', error); }
async function api(url, options) { const response = await fetch(url, options); const result = await response.json(); if (!response.ok) throw new Error(result.error || `Request failed (${response.status}).`); return result; }
async function loadData() { data = await api('/api/data'); aliases = new Map([...new Set(data.transactions.map(r => r.username))].sort().map((n, i) => [n, `Recipient ${String(i + 1).padStart(2, '0')}`])); $('saved').textContent = data.exists ? `Saved ${new Date(data.saved_at).toLocaleString()} · ${fmt(data.transactions.length)} transactions` : 'No saved history yet. Pull new data to get started.'; render(); if (data.skipped) message(`${data.skipped} invalid or duplicate records were excluded from the charts.`); }
async function checkStatus() { const s = await api('/api/status'); refreshToken = s.refresh_token; $('refresh').disabled = s.running; $('refresh').textContent = s.running ? '↻ Pulling history…' : '↻ Pull new data'; return s; }
async function poll() { if (polling) return; polling = true; try { let s = await checkStatus(); while (s.running) { message(s.message); await new Promise(r => setTimeout(r, 900)); s = await checkStatus(); } if (s.error) message(s.error, true); else { await loadData(); message(s.message || 'Saved history loaded.'); } } catch (e) { message(`${e.message} Reload this page to reconnect to the refresh status.`, true); $('refresh').disabled = false; } finally { polling = false; } }
$('refresh').onclick = async () => { try { $('refresh').disabled = true; const s = await checkStatus(); if (!s.running) { $('refresh').disabled = true; await api('/api/refresh', { method: 'POST', headers: { 'X-Refresh-Token': refreshToken } }); } await poll(); } catch (e) { message(e.message, true); $('refresh').disabled = false; } };
$('theme').onclick = () => setTheme(theme === 'dark' ? 'light' : 'dark');
$('privacy').onclick = () => { hiddenNames = !hiddenNames; $('privacy').setAttribute('aria-pressed', String(hiddenNames)); $('privacy').textContent = hiddenNames ? '◎ Show names' : '◎ Hide names'; $('search').value = ''; $('tooltip').hidden = true; render(); };
$('filters').onsubmit = e => e.preventDefault();['from', 'to', 'mode'].forEach(id => $(id).onchange = () => { message(''); render(); });
$('reset').onclick = () => { $('from').value = ''; $('to').value = ''; $('mode').value = 'all'; message(''); render(); };
['search', 'category', 'sort'].forEach(id => $(id).addEventListener(id === 'search' ? 'input' : 'change', () => { page = 0; renderTransactions(); }));
$('prev').onclick = () => { page--; renderTransactions(); }; $('next').onclick = () => { page++; renderTransactions(); };
$('payment-method').onchange = renderReferences; $('level').oninput = renderLevel;
$('export').onclick = () => { const cell = v => { let s = String(v ?? ''); if (/^[=+@\-\t\r]/.test(s) && typeof v !== 'number') s = "'" + s; return '"' + s.replace(/"/g, '""') + '"'; }; const rows = [['Date UTC', 'Recipient', 'Type', 'VR', 'Tokens', 'Category', 'Transaction ID'], ...tableRows.map(r => [r.date, name(r.username), r.type, r.vr, r.tokens, r.purchase ? 'purchase' : r.spending ? 'spending' : 'other', hiddenNames ? '' : r.id])]; const url = URL.createObjectURL(new Blob(['\ufeff' + rows.map(r => r.map(cell).join(',')).join('\r\n')], { type: 'text/csv;charset=utf-8' })); const a = document.createElement('a'); a.href = url; a.download = 'ledger-transactions.csv'; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); };
document.addEventListener('pointermove', e => { const target = e.target.closest('[data-tip]'), tip = $('tooltip'); if (!target) { tip.hidden = true; return; } tip.textContent = target.dataset.tip; tip.hidden = false; tip.style.left = `${Math.max(8, Math.min(e.clientX + 14, innerWidth - tip.offsetWidth - 10))}px`; tip.style.top = `${Math.max(8, Math.min(e.clientY + 14, innerHeight - tip.offsetHeight - 10))}px`; });
document.addEventListener('pointerleave', () => { $('tooltip').hidden = true; });
document.querySelectorAll('a[href^="#"]').forEach(link => link.addEventListener('click', event => { const section = document.querySelector(link.getAttribute('href')); if (section) { event.preventDefault(); section.scrollIntoView({ behavior: matchMedia('(prefers-reduced-motion: reduce)').matches ? 'instant' : 'smooth', block: 'start' }); history.replaceState(null, '', link.getAttribute('href')); } }));
let resizeTimer; window.addEventListener('resize', () => { clearTimeout(resizeTimer); resizeTimer = setTimeout(() => { const oldPage = page; render(); page = oldPage; renderTransactions(); renderReferences(); }, 180); });
const observer = new IntersectionObserver(entries => { const visible = entries.filter(e => e.isIntersecting).sort((a, b) => a.boundingClientRect.top - b.boundingClientRect.top); if (visible.length) document.querySelectorAll('nav a').forEach(a => a.classList.toggle('active', a.hash === '#' + visible[0].target.id)); }, { rootMargin: '-5% 0px -65% 0px' }); document.querySelectorAll('main section').forEach(s => observer.observe(s));
(async () => { try { reference = await api('/reference.json'); $('payment-method').insertAdjacentHTML('beforeend', Object.keys(reference).filter(k => k.endsWith('_packages')).map(k => `<option value="${esc(k)}">${esc(friendly(k.replace('_packages', '')))}</option>`).join('')); renderReferences(); await loadData(); const s = await checkStatus(); if (s.running) poll(); else if (s.error) message(s.error, true); } catch (e) { message(e.message, true); } })();
